RLEnvironment-ANY:
  normalize: false
  n_envs: 1
  policy: 'MlpPolicy'
  n_timesteps: -1
  batch_size: 64
  n_steps: 2048
  gamma: 0.99
  learning_rate: !!float 3e-4
  ent_coef: 0.0
  clip_range: 0.2
  n_epochs: 10
  gae_lambda: 0.95
  max_grad_norm: 0.5
  vf_coef: 0.5