from flowing_basin.core import Instance
from .dam import Dam


class RiverBasin:
    def __init__(self, instance: Instance, path_power_model: str):

        # Dams inside the flowing basin
        self.dams = []
        num_dams = instance.get_num_dams()
        for idx in range(1, num_dams + 1):
            dam = Dam(
                idx="dam" + str(idx),
                instance=instance,
                path_power_model=path_power_model,
            )
            self.dams.append(dam)

        # Identifier of the time step (increases with each update)
        self.time = 0

        # Save instance to get incoming flows in the update method
        self.instance = instance

    def update(self, flows: dict[str, float]) -> None:

        """

        :param flows: Dictionary of flows that should go through each channel, indexed by dam
        """

        # The first dam has no preceding dam
        turbined_flow_of_preceding_dam = 0

        # Update dams
        for dam in self.dams:
            turbined_flow = dam.update(
                flows=flows,
                incoming_flow=self.instance.get_incoming_flow(self.time),
                turbined_flow_of_preceding_dam=turbined_flow_of_preceding_dam,
            )
            turbined_flow_of_preceding_dam = turbined_flow

        # Increase time step identifier to get the next incoming flow
        self.time = self.time + 1

    def get_state(self):

        """
        Returns the state of the river basin
        (volume of every dam, flow through each channel, power generated by every power group, etc.)
        :return:
        """

        volumes = []
        unregulated_flows = []
        incoming_flow = self.instance.get_incoming_flow(self.time)
        lags = []

        for dam in self.dams:
            volumes.append(dam.volume)
            unregulated_flows.append(dam.unregulated_flow)
            lags.append(dam.channel.flows_over_time)

        return volumes, unregulated_flows, incoming_flow, lags
